import type { SyntheticPatient } from '@/types/patient.types'

export const patients: SyntheticPatient[] = [
  {
    id: 'patient-001',
    firstName: 'Maria',
    lastName: 'Gonzalez',
    dateOfBirth: '1985-03-14',
    memberId: '990122445',
    groupNumber: 'GRP001234',
    payerId: '87726',
    insurancePlan: 'UHC Gold PPO 2024',
    primaryCareProvider: 'Dr. Adaeze Okafor',
    scenario: 'ROUTINE_VISIT_LOW_COST',
    scenarioLabel: 'Routine Visit — Low Cost',
    scenarioDescription:
      'Routine PCP follow-up visit. Deductible is already met for the plan year, so only a standard copay applies.',
    procedureContext: {
      code: '99213',
      description: 'Office/outpatient visit, established patient, low complexity',
      serviceTypeCode: '30',
      serviceTypeLabel: 'Health Benefit Plan Coverage',
      typicalDuration: '15 minutes',
    },
    subscriberFirstName: 'MARIA',
    subscriberLastName: 'GONZALEZ',
    subscriberDob: '19850314',
    npi: '1234567890',
    mockEligibilityScenario: 'active_full_coverage',
    mockBenefitScenario: 'deductible_met_low_copay',
  },
  {
    id: 'patient-002',
    firstName: 'James',
    lastName: 'Washington',
    dateOfBirth: '1972-08-22',
    memberId: '990133556',
    groupNumber: 'GRP005678',
    payerId: '87726',
    insurancePlan: 'UHC Platinum HMO 2024',
    primaryCareProvider: 'Dr. Samuel Greenfield',
    scenario: 'SPECIALIST_MID_RANGE',
    scenarioLabel: 'Specialist Consult — Mid Range',
    scenarioDescription:
      'Specialist consultation referral. Deductible is partially met at $800 of $2,000, resulting in a combination of remaining deductible and coinsurance.',
    procedureContext: {
      code: '99243',
      description: 'Office consultation for new or established patient, moderate complexity',
      serviceTypeCode: '30',
      serviceTypeLabel: 'Health Benefit Plan Coverage',
      typicalDuration: '40 minutes',
    },
    subscriberFirstName: 'JAMES',
    subscriberLastName: 'WASHINGTON',
    subscriberDob: '19720822',
    npi: '1234567890',
    mockEligibilityScenario: 'active_standard',
    mockBenefitScenario: 'deductible_partial_coinsurance',
  },
  {
    id: 'patient-003',
    firstName: 'Aisha',
    lastName: 'Rahman',
    dateOfBirth: '1991-11-05',
    memberId: '990144667',
    groupNumber: 'GRP009012',
    payerId: '87726',
    insurancePlan: 'UHC Bronze HSA 2024',
    primaryCareProvider: 'Dr. Linda Reyes',
    scenario: 'IMAGING_HIGH_COST',
    scenarioLabel: 'Imaging — High Cost',
    scenarioDescription:
      'Outpatient imaging study on a high-deductible Bronze plan. Only $1,200 of the $3,000 deductible has been met, creating significant out-of-pocket exposure.',
    procedureContext: {
      code: '73721',
      description: 'MRI any joint of lower extremity without contrast',
      serviceTypeCode: '30',
      serviceTypeLabel: 'Health Benefit Plan Coverage',
      typicalDuration: '45 minutes',
    },
    subscriberFirstName: 'AISHA',
    subscriberLastName: 'RAHMAN',
    subscriberDob: '19911105',
    npi: '1234567890',
    mockEligibilityScenario: 'active_high_deductible',
    mockBenefitScenario: 'deductible_not_met_imaging',
  },
  {
    id: 'patient-004',
    firstName: 'Robert',
    lastName: 'Chen',
    dateOfBirth: '1968-05-30',
    memberId: '990155778',
    groupNumber: 'GRP003456',
    payerId: '87726',
    insurancePlan: 'UHC Choice Plus PPO 2024',
    primaryCareProvider: 'Dr. Michael Petrov',
    scenario: 'PREVENTIVE_ZERO_COST',
    scenarioLabel: 'Preventive Care — Zero Cost',
    scenarioDescription:
      'Annual wellness exam. Under ACA guidelines, preventive services are covered at 100% with no cost-sharing regardless of deductible status.',
    procedureContext: {
      code: '99395',
      description: 'Periodic comprehensive preventive medicine, 18-39 years',
      serviceTypeCode: '30',
      serviceTypeLabel: 'Health Benefit Plan Coverage',
      typicalDuration: '30 minutes',
    },
    subscriberFirstName: 'ROBERT',
    subscriberLastName: 'CHEN',
    subscriberDob: '19680530',
    npi: '1234567890',
    mockEligibilityScenario: 'active_hdhp',
    mockBenefitScenario: 'preventive_fully_covered',
  },
  {
    id: 'patient-005',
    firstName: 'Destiny',
    lastName: 'Williams',
    dateOfBirth: '2001-09-17',
    memberId: '990166889',
    groupNumber: 'GRP007890',
    payerId: '87726',
    insurancePlan: 'UHC Student Health Plan',
    primaryCareProvider: 'Dr. Angela Torres',
    scenario: 'EMERGENCY_HIGH_EXPOSURE',
    scenarioLabel: 'Emergency Room — High Exposure',
    scenarioDescription:
      'Emergency department visit on a student health plan with a high deductible. Only $500 of the $5,000 deductible has been met, resulting in a flat ER copay plus deductible and coinsurance.',
    procedureContext: {
      code: '99284',
      description: 'Emergency department visit, high complexity',
      serviceTypeCode: '30',
      serviceTypeLabel: 'Health Benefit Plan Coverage',
      typicalDuration: '3 hours',
    },
    subscriberFirstName: 'DESTINY',
    subscriberLastName: 'WILLIAMS',
    subscriberDob: '20010917',
    npi: '1234567890',
    mockEligibilityScenario: 'active_high_deductible_er',
    mockBenefitScenario: 'high_deductible_er_exposure',
  },
  {
    id: 'patient-006',
    firstName: 'Thomas',
    lastName: "O'Brien",
    dateOfBirth: '1955-01-08',
    memberId: '990177990',
    groupNumber: 'GRP002345',
    payerId: '87726',
    insurancePlan: 'UHC Medicare Advantage PPO',
    primaryCareProvider: 'Dr. Rachel Kim',
    scenario: 'BEHAVIORAL_HEALTH_CARVEOUT',
    scenarioLabel: 'Behavioral Health — Carve-Out',
    scenarioDescription:
      'Outpatient behavioral health session. This plan has a behavioral health carve-out with a flat copay and no coinsurance. Deductible is already fully met.',
    procedureContext: {
      code: '90834',
      description: 'Psychotherapy, 45 minutes with patient',
      serviceTypeCode: '30',
      serviceTypeLabel: 'Health Benefit Plan Coverage',
      typicalDuration: '45 minutes',
    },
    subscriberFirstName: 'THOMAS',
    subscriberLastName: 'OBRIEN',
    subscriberDob: '19550108',
    npi: '1234567890',
    mockEligibilityScenario: 'active_bh_carveout',
    mockBenefitScenario: 'behavioral_health_copay_only',
  },
  {
    id: 'patient-007',
    firstName: 'David',
    lastName: 'Washington',
    dateOfBirth: '1972-08-22',
    memberId: '990133556',
    groupNumber: 'GRP005678',
    payerId: '87726',
    insurancePlan: 'UHC Platinum HMO 2024',
    primaryCareProvider: 'Dr. Brian Whitfield',
    scenario: 'THERAPY_LIMIT_APPROACHING',
    scenarioLabel: 'Physical Therapy — Visit Limit Approaching',
    scenarioDescription:
      'Physical therapy session with 16 of 20 annual visits already used. Deductible is met, so a flat copay applies, but the visit limit requires attention.',
    procedureContext: {
      code: '97110',
      description: 'Therapeutic exercises to develop strength, endurance, flexibility',
      serviceTypeCode: '30',
      serviceTypeLabel: 'Health Benefit Plan Coverage',
      typicalDuration: '30 minutes',
    },
    subscriberFirstName: 'JAMES',
    subscriberLastName: 'WASHINGTON',
    subscriberDob: '19720822',
    npi: '1234567890',
    mockEligibilityScenario: 'active_visit_limit',
    mockBenefitScenario: 'pt_visit_limit_approaching',
  },
]

export function getPatientById(id: string): SyntheticPatient | undefined {
  return patients.find((p) => p.id === id)
}
