from semantic_kernel.functions import kernel_function


class RiskPlugin:
    """Semantic Kernel plugin: assess financial risk and generate action items."""

    @kernel_function(
        name="assess_risk_flags",
        description="Assess the patient's financial risk level and generate actionable next steps for billing staff.",
    )
    async def assess_risk_flags(
        self, cost_summary: str, benefit_summary: str
    ) -> str:
        return f"""Assess the financial risk level and generate action items for this patient visit.

RISK LEVEL RULES:
- HIGH: remaining deductible exceeds $2,000, OR estimated total exceeds $1,000, OR prior authorization is required but not confirmed
- MEDIUM: coinsurance exceeds 20%, OR visit limits are 80%+ used, OR estimated total is $200-$1,000
- LOW: moderate cost-sharing but manageable
- NONE: $0 cost (preventive care) or very low cost with high confidence

ACTION ITEMS RULES:
- Must be practical steps a patient or billing coordinator can take
- Include specific dollar amounts where applicable
- Flag prior authorization requirements
- Flag approaching visit limits
- Suggest payment plan for high-cost visits

Cost Summary:
{cost_summary}

Benefit Summary:
{benefit_summary}

Return a JSON object with these fields:
- riskFlag: "HIGH" | "MEDIUM" | "LOW" | "NONE"
- actionItems: array of 2-4 practical action item strings
- authorizationRequired: boolean
- authorizationNote: string (empty if no auth required)
- deductibleStatus: string summarizing deductible status
- visitLimitStatus: string summarizing visit limits
- coverageConfirmation: string confirming coverage status
- sandboxNote: "Results generated by Azure Semantic Kernel pipeline with GPT-5.4."

Return ONLY valid JSON. No markdown, no prose, no backticks."""
